// Mocks generated by Mockito 5.4.4 from annotations
// in api_fake_storage_orm/test/src/domain/repositories/cart_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:api_fake_storage_orm/api_fake_storage_orm.dart' as _i7;
import 'package:api_fake_storage_orm/src/data/api/cart/error/cart_exception.dart'
    as _i5;
import 'package:api_fake_storage_orm/src/domain/repositories/cart_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_models_commons/flutter_models_commons.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i3.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i2.Either<_i5.CartApiException, List<_i6.CartApiModel>>> getAllCarts(
    _i7.Sort? sort,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCarts,
          [
            sort,
            limit,
          ],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.CartApiException, List<_i6.CartApiModel>>>.value(
            _FakeEither_0<_i5.CartApiException, List<_i6.CartApiModel>>(
          this,
          Invocation.method(
            #getAllCarts,
            [
              sort,
              limit,
            ],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.CartApiException, List<_i6.CartApiModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.CartApiException, _i6.CartApiModel>> getCartById(
          int? cartId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCartById,
          [cartId],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.CartApiException, _i6.CartApiModel>>.value(
            _FakeEither_0<_i5.CartApiException, _i6.CartApiModel>(
          this,
          Invocation.method(
            #getCartById,
            [cartId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.CartApiException, _i6.CartApiModel>>);

  @override
  _i4.Future<_i2.Either<_i5.CartApiException, _i6.CartApiModel>>
      getCartByUserId(int? userId) => (super.noSuchMethod(
            Invocation.method(
              #getCartByUserId,
              [userId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.CartApiException, _i6.CartApiModel>>.value(
                _FakeEither_0<_i5.CartApiException, _i6.CartApiModel>(
              this,
              Invocation.method(
                #getCartByUserId,
                [userId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.CartApiException, _i6.CartApiModel>>);

  @override
  _i4.Future<_i2.Either<_i5.CartApiException, int>> addCart(
    int? userId,
    List<_i6.ProductCartApi>? products,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCart,
          [
            userId,
            products,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.CartApiException, int>>.value(
            _FakeEither_0<_i5.CartApiException, int>(
          this,
          Invocation.method(
            #addCart,
            [
              userId,
              products,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.CartApiException, int>>);

  @override
  _i4.Future<_i2.Either<_i5.CartApiException, int>> updateProductsCart(
    int? cartId,
    int? userId,
    List<_i6.ProductCartApi>? products,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProductsCart,
          [
            cartId,
            userId,
            products,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.CartApiException, int>>.value(
            _FakeEither_0<_i5.CartApiException, int>(
          this,
          Invocation.method(
            #updateProductsCart,
            [
              cartId,
              userId,
              products,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.CartApiException, int>>);

  @override
  _i4.Future<_i2.Either<_i5.CartApiException, _i6.CartApiModel>> deleteCart(
          int? cartId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCart,
          [cartId],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.CartApiException, _i6.CartApiModel>>.value(
            _FakeEither_0<_i5.CartApiException, _i6.CartApiModel>(
          this,
          Invocation.method(
            #deleteCart,
            [cartId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.CartApiException, _i6.CartApiModel>>);
}
